<?php

declare(strict_types=1);

namespace OCA\ProjectCheck\Tests\Integration;

use OCA\ProjectCheck\Migration\RateHistoryTables;
use OCA\ProjectCheck\Service\UpgradeBackupCatalog;
use OCA\ProjectCheck\Service\UpgradeBackupService;
use OCP\IConfig;
use OCP\IDBConnection;
use Test\TestCase;

/**
 * Canonical multi-table upgrade-backup integration coverage for ProjectCheck.
 *
 * Not generated by sync-upgrade-backup.php — extend here for audit-grade restore tests.
 */
final class UpgradeBackupMultiTableIntegrationTest extends TestCase
{
	private const FIXTURE_MARKER = 'PC_UPGRADE_BACKUP_IT';
	private const FIXTURE_USER = 'pc_upgrade_backup_it';
	private const CONFIG_MARKER_KEY = 'integration_test_marker';

	private UpgradeBackupService $backupService;
	private IDBConnection $db;
	private IConfig $config;

	/** @var list<int> */
	private array $fixtureCustomerIds = [];

	/** @var list<int> */
	private array $fixtureProjectIds = [];

	protected function setUp(): void
	{
		parent::setUp();
		$this->backupService = \OC::$server->get(UpgradeBackupService::class);
		$this->db = \OC::$server->get(IDBConnection::class);
		$this->config = \OC::$server->get(IConfig::class);
	}

	protected function tearDown(): void
	{
		$this->removeFixtureRows();
		$this->config->deleteAppValue(UpgradeBackupCatalog::APP_ID, self::CONFIG_MARKER_KEY);
		parent::tearDown();
	}

	public function testFullCatalogTablesRestoreRoundTrip(): void
	{
		$existingTables = $this->existingBackupTables();
		if ($existingTables === []) {
			self::markTestSkipped('ProjectCheck tables not present in this instance.');
		}

		if (!$this->canSeedRelationalFixture()) {
			self::markTestSkipped('Core ProjectCheck tables required for multi-table restore test are missing.');
		}

		$this->seedRelationalFixture();
		$markerValue = self::FIXTURE_MARKER . '-' . bin2hex(random_bytes(4));
		$this->config->setAppValue(UpgradeBackupCatalog::APP_ID, self::CONFIG_MARKER_KEY, $markerValue);

		$beforeCounts = $this->captureRowCounts($existingTables);
		self::assertNotEmpty($beforeCounts, 'At least one catalog table must contain rows after seeding.');

		$result = $this->backupService->createSnapshot('integration-multi-table');
		$snapshotId = $result['id'];
		/** @var array<string, array<string, mixed>> $manifestTables */
		$manifestTables = $result['manifest']['tables'] ?? [];

		foreach (array_keys($beforeCounts) as $table) {
			self::assertArrayHasKey(
				$table,
				$manifestTables,
				'Snapshot manifest must include every non-empty catalog table: ' . $table,
			);
			self::assertSame(
				$beforeCounts[$table],
				(int)($manifestTables[$table]['rowCount'] ?? -1),
				'Manifest row count must match database for ' . $table,
			);
		}

		$this->wipeBackupTables($existingTables);
		foreach ($beforeCounts as $table => $count) {
			self::assertSame(0, $this->countRows($table), 'Wipe must empty ' . $table);
		}

		$this->config->setAppValue(UpgradeBackupCatalog::APP_ID, self::CONFIG_MARKER_KEY, 'corrupted-by-test');

		$this->backupService->restoreSnapshot($snapshotId, false);

		foreach ($beforeCounts as $table => $count) {
			self::assertSame(
				$count,
				$this->countRows($table),
				'Restore must recover row count for ' . $table,
			);
		}

		self::assertSame(
			$markerValue,
			$this->config->getAppValue(UpgradeBackupCatalog::APP_ID, self::CONFIG_MARKER_KEY),
			'Restore must recover app config written before the snapshot.',
		);

		self::assertFixtureChainIntact();
	}

	/**
	 * @return list<string>
	 */
	private function existingBackupTables(): array
	{
		return UpgradeBackupCatalog::existingBackupTables(
			fn (string $table): bool => $this->db->tableExists($table),
		);
	}

	private function canSeedRelationalFixture(): bool
	{
		foreach (['pc_customers', 'pc_projects', 'pc_project_members', 'pc_time_entries'] as $table) {
			if (!$this->db->tableExists($table)) {
				return false;
			}
		}

		return true;
	}

	private function seedRelationalFixture(): void
	{
		$actor = self::FIXTURE_USER;
		$now = (new \DateTimeImmutable('now', new \DateTimeZone('UTC')))->format('Y-m-d H:i:s');
		$today = (new \DateTimeImmutable('now', new \DateTimeZone('UTC')))->format('Y-m-d');
		$markerName = self::FIXTURE_MARKER . '-' . bin2hex(random_bytes(4));

		$customerId = $this->insertRow('pc_customers', [
			'name' => $markerName,
			'created_by' => $actor,
			'created_at' => $now,
			'updated_at' => $now,
		]);
		$this->fixtureCustomerIds[] = $customerId;

		$projectId = $this->insertRow('pc_projects', [
			'name' => $markerName . ' project',
			'short_description' => 'upgrade backup integration fixture',
			'customer_id' => $customerId,
			'hourly_rate' => '100.00',
			'total_budget' => '10000.00',
			'available_hours' => '100.00',
			'status' => 'Active',
			'created_by' => $actor,
			'created_at' => $now,
			'updated_at' => $now,
			'project_type' => 'client',
			'cost_rate_mode' => 'project',
		]);
		$this->fixtureProjectIds[] = $projectId;

		$this->insertRow('pc_project_members', [
			'project_id' => $projectId,
			'user_id' => $actor,
			'role' => 'member',
			'assigned_at' => $now,
			'assigned_by' => $actor,
			'member_state' => 'active',
		]);

		$this->insertRow('pc_time_entries', [
			'project_id' => $projectId,
			'user_id' => $actor,
			'date' => $today,
			'hours' => '1.50',
			'description' => self::FIXTURE_MARKER,
			'hourly_rate' => '100.00',
			'created_at' => $now,
			'updated_at' => $now,
		]);

		if ($this->db->tableExists(RateHistoryTables::EMPLOYEE)) {
			$this->insertRow(RateHistoryTables::EMPLOYEE, [
				'user_id' => $actor,
				'hourly_rate' => '95.0000',
				'effective_from' => $today,
				'created_by' => $actor,
				'created_at' => $now,
			]);
		}

		if ($this->db->tableExists(RateHistoryTables::PROJECT_MEMBER)) {
			$this->insertRow(RateHistoryTables::PROJECT_MEMBER, [
				'project_id' => $projectId,
				'user_id' => $actor,
				'hourly_rate' => '105.0000',
				'effective_from' => $today,
				'created_by' => $actor,
				'created_at' => $now,
			]);
		}
	}

	private function assertFixtureChainIntact(): void
	{
		self::assertNotSame([], $this->fixtureCustomerIds);
		self::assertNotSame([], $this->fixtureProjectIds);

		$customerId = $this->fixtureCustomerIds[0];
		$projectId = $this->fixtureProjectIds[0];

		$qb = $this->db->getQueryBuilder();
		$qb->select('name')
			->from('pc_customers')
			->where($qb->expr()->eq('id', $qb->createNamedParameter($customerId)));
		$customerName = (string)$qb->executeQuery()->fetchOne();

		self::assertStringStartsWith(self::FIXTURE_MARKER, $customerName);

		$qb = $this->db->getQueryBuilder();
		$qb->select('customer_id')
			->from('pc_projects')
			->where($qb->expr()->eq('id', $qb->createNamedParameter($projectId)));
		self::assertSame($customerId, (int)$qb->executeQuery()->fetchOne());

		$qb = $this->db->getQueryBuilder();
		$qb->select($qb->func()->count('*', 'cnt'))
			->from('pc_project_members')
			->where($qb->expr()->eq('project_id', $qb->createNamedParameter($projectId)));
		self::assertSame(1, (int)$qb->executeQuery()->fetchOne());

		$qb = $this->db->getQueryBuilder();
		$qb->select($qb->func()->count('*', 'cnt'))
			->from('pc_time_entries')
			->where($qb->expr()->eq('project_id', $qb->createNamedParameter($projectId)))
			->andWhere($qb->expr()->eq('description', $qb->createNamedParameter(self::FIXTURE_MARKER)));
		self::assertSame(1, (int)$qb->executeQuery()->fetchOne());
	}

	private function removeFixtureRows(): void
	{
		if ($this->fixtureProjectIds === [] && $this->fixtureCustomerIds === []) {
			return;
		}

		foreach ($this->fixtureProjectIds as $projectId) {
			foreach (['pc_time_entries', 'pc_project_members', RateHistoryTables::PROJECT_MEMBER] as $table) {
				if (!$this->db->tableExists($table)) {
					continue;
				}
				$qb = $this->db->getQueryBuilder();
				$qb->delete($table)
					->where($qb->expr()->eq('project_id', $qb->createNamedParameter($projectId)))
					->executeStatement();
			}

			if ($this->db->tableExists('pc_projects')) {
				$qb = $this->db->getQueryBuilder();
				$qb->delete('pc_projects')
					->where($qb->expr()->eq('id', $qb->createNamedParameter($projectId)))
					->executeStatement();
			}
		}

		foreach ($this->fixtureCustomerIds as $customerId) {
			if ($this->db->tableExists('pc_customers')) {
				$qb = $this->db->getQueryBuilder();
				$qb->delete('pc_customers')
					->where($qb->expr()->eq('id', $qb->createNamedParameter($customerId)))
					->executeStatement();
			}
		}

		if ($this->db->tableExists(RateHistoryTables::EMPLOYEE)) {
			$qb = $this->db->getQueryBuilder();
			$qb->delete(RateHistoryTables::EMPLOYEE)
				->where($qb->expr()->eq('user_id', $qb->createNamedParameter(self::FIXTURE_USER)))
				->executeStatement();
		}

		$this->fixtureProjectIds = [];
		$this->fixtureCustomerIds = [];
	}

	/**
	 * @param list<string> $tables
	 * @return array<string, int>
	 */
	private function captureRowCounts(array $tables): array
	{
		$counts = [];
		foreach ($tables as $table) {
			$count = $this->countRows($table);
			if ($count > 0) {
				$counts[$table] = $count;
			}
		}

		return $counts;
	}

	/**
	 * @param list<string> $tables
	 */
	private function wipeBackupTables(array $tables): void
	{
		$ordered = UpgradeBackupCatalog::sortedRestoreTables($tables);
		foreach (array_reverse($ordered) as $table) {
			if (!$this->db->tableExists($table)) {
				continue;
			}
			$this->db->getQueryBuilder()
				->delete($table)
				->executeStatement();
		}
	}

	/**
	 * @param array<string, mixed> $values
	 */
	private function insertRow(string $table, array $values): int
	{
		$qb = $this->db->getQueryBuilder();
		$qb->insert($table);
		foreach ($values as $column => $value) {
			$qb->setValue((string)$column, $qb->createNamedParameter($value));
		}
		$qb->executeStatement();

		return $this->db->lastInsertId($table);
	}

	private function countRows(string $table): int
	{
		$qb = $this->db->getQueryBuilder();
		$qb->select($qb->func()->count('*', 'cnt'))
			->from($table);
		$result = $qb->executeQuery();
		$count = (int)$result->fetchOne();
		$result->closeCursor();

		return $count;
	}
}
